name: Publish NPM
on:
  push:
    branches:
      - next
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: next
          
      # Set up Node.js environment for GitHub Packages publishing
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'

      # Install project dependencies
      - name: Install Dependencies
        run: npm install

      # If you have a build process, include it
      - name: Build
        run: npm run build

      # Publish the package to GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
