name: Build and Push to Dist Branch

on:
  push:
    branches:
      - master # or whatever your primary branch is

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up Node.js environment for GitHub Packages publishing
    - name: Setup Node.js
      uses: actions/setup-node@v3.8.1
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Push Built Files to Dist Branch
      run: |
        git checkout -b dist
        git add -A
        git commit -m "Built for commit ${{ github.sha }}"
        git push -f origin dist
