name: Publish NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: next
          
      # Set up Node.js environment for GitHub Packages publishing
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'

      # Install project dependencies
      - name: Install Dependencies
        run: npm install

      # If you have a build process, include it
      - name: Build
        run: npm run build

      # Set version number based on GitHub release
      - name: Set version in package.json
        run: |
          RELEASE_VERSION=${{ github.event.release.tag_name }}
          jq '.version = "${RELEASE_VERSION}"' package.json > package.tmp.json && mv package.tmp.json package.json

      # Publish the package to GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
